# Chromium
dot_desktop_path = [
    "/usr/share/applications/org.chromium.Chromium.desktop",
    "/usr/share/applications/chromium-browser.desktop",
    "/usr/share/applications/chromium.desktop",
]
description='''
Chromium web browser.
'''

import_tips='''
Move .config/chromium folder from your home directory in to instance
home directory.
'''

[services.common]
executable_name = "/usr/bin/chromium"
[services.x11]
[services.network]
[services.pulse_audio]
[services.notify]
[services.direct_rendering]
[services.home_share]
home_paths = ["Downloads",]
[services.mpris]
player_name = "chromium.*"
