# IntelliJ IDEA Ultimate on Wayland
dot_desktop_path = "/usr/share/applications/jetbrains-idea-u.desktop"
description='''
IntelliJ IDEA Ultimate using wayland display protocol.

Given access to ~/Projects by default.
'''

import_tips='''
Move .local/share/JetBrains, .cache/JetBrains and .config/JetBrains folders
from your home directory in to instance home directory to keep your
settings, plugins and license.

Make sure ~/.local/share/JetBrains/Toolbox/scripts is in PATH inside the
instance so the "idea" launcher script can be found.
'''

[services.common]
executable_name = "idea"
[services.wayland]
[services.network]
[services.notify]
[services.direct_rendering]
[services.home_share]
home_paths = ["Projects", ".local/share/JetBrains", ".cache/JetBrains", ".config/JetBrains",]
