# Visual Studio Code
dot_desktop_path = "/usr/share/applications/code.desktop"
description='''
Visual Studio Code, Microsoft's source code editor.

Given access to ~/Projects by default.
'''

import_tips='''
Move .config/Code and .vscode folders from your home directory in to
instance home directory to keep extensions and settings.
'''

[services.common]
executable_name = "/usr/bin/code"
[services.x11]
[services.network]
[services.notify]
[services.direct_rendering]
[services.home_share]
home_paths = ["Projects",]
